/* paths.h: Generated from texmf.cnf. */

#define DEFAULT_TEXPATH ""

#ifndef DEFAULT_TEXMFROOT
//#define DEFAULT_TEXMFROOT "$SELFAUTOPARENT"
#define DEFAULT_TEXMFROOT DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMFDIST
#define DEFAULT_TEXMFDIST DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMFMAIN
#define DEFAULT_TEXMFMAIN DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMFLOCAL
//#define DEFAULT_TEXMFLOCAL "$SELFAUTOGRANDPARENT/texmf-local"
#define DEFAULT_TEXMFLOCAL DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMFSYSVAR
#define DEFAULT_TEXMFSYSVAR DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMFSYSCONFIG
#define DEFAULT_TEXMFSYSCONFIG DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMFHOME
#define DEFAULT_TEXMFHOME DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMFVAR
#define DEFAULT_TEXMFVAR DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMFCONFIG
#define DEFAULT_TEXMFCONFIG DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMFAUXTREES
#define DEFAULT_TEXMFAUXTREES DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMF
#define DEFAULT_TEXMF DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMFDBS
#define DEFAULT_TEXMFDBS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_SYSTEXMF
#define DEFAULT_SYSTEXMF DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMFCACHE
#define DEFAULT_TEXMFCACHE DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_VARTEXFONTS
#define DEFAULT_VARTEXFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_WEB2C
#define DEFAULT_WEB2C DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMFDOTDIR
#define DEFAULT_TEXMFDOTDIR DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXINPUTS
#define DEFAULT_TEXINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_MFINPUTS
#define DEFAULT_MFINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_MPINPUTS
#define DEFAULT_MPINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXFORMATS
#define DEFAULT_TEXFORMATS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_MFBASES
#define DEFAULT_MFBASES DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_MPMEMS
#define DEFAULT_MPMEMS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXPOOL
#define DEFAULT_TEXPOOL DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_MFPOOL
#define DEFAULT_MFPOOL DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_MPPOOL
#define DEFAULT_MPPOOL DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_VFFONTS
#define DEFAULT_VFFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TFMFONTS
#define DEFAULT_TFMFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_PKFONTS
#define DEFAULT_PKFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_GFFONTS
#define DEFAULT_GFFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_GLYPHFONTS
#define DEFAULT_GLYPHFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_MISCFONTS
#define DEFAULT_MISCFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXFONTMAPS
#define DEFAULT_TEXFONTMAPS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_BIBINPUTS
#define DEFAULT_BIBINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_BSTINPUTS
#define DEFAULT_BSTINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_MLBIBINPUTS
#define DEFAULT_MLBIBINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_MLBSTINPUTS
#define DEFAULT_MLBSTINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_RISINPUTS
#define DEFAULT_RISINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_BLTXMLINPUTS
#define DEFAULT_BLTXMLINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_MFTINPUTS
#define DEFAULT_MFTINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXPSHEADERS
#define DEFAULT_TEXPSHEADERS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_OSFONTDIR
//#define DEFAULT_OSFONTDIR "/please/set/osfontdir/in/the/environment"
#define DEFAULT_OSFONTDIR DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_T1FONTS
#define DEFAULT_T1FONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_AFMFONTS
#define DEFAULT_AFMFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TTFONTS
#define DEFAULT_TTFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_OPENTYPEFONTS
#define DEFAULT_OPENTYPEFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_T42FONTS
#define DEFAULT_T42FONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_LIGFONTS
#define DEFAULT_LIGFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXCONFIG
#define DEFAULT_TEXCONFIG DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_INDEXSTYLE
#define DEFAULT_INDEXSTYLE DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_INDEXDICTIONARY
#define DEFAULT_INDEXDICTIONARY DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_ENCFONTS
#define DEFAULT_ENCFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_CMAPFONTS
#define DEFAULT_CMAPFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_SFDFONTS
#define DEFAULT_SFDFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_FONTFEATURES
#define DEFAULT_FONTFEATURES DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_FONTCIDMAPS
#define DEFAULT_FONTCIDMAPS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_PDFTEXCONFIG
#define DEFAULT_PDFTEXCONFIG DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TRFONTS
//#define DEFAULT_TRFONTS "/usr{/local,}/share/groff/{current/font,site-font}/devps"
#define DEFAULT_TRFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_MPSUPPORT
#define DEFAULT_MPSUPPORT DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_MIMELIBDIR
#define DEFAULT_MIMELIBDIR DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_MAILCAPLIBDIR
#define DEFAULT_MAILCAPLIBDIR DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_FONTCONFIG_FILE
#define DEFAULT_FONTCONFIG_FILE DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_XE_FONTCONFIG_PATH
#define DEFAULT_XE_FONTCONFIG_PATH DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_XE_FC_CACHEDIR
#define DEFAULT_XE_FC_CACHEDIR DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXDOCS
#define DEFAULT_TEXDOCS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXSOURCES
#define DEFAULT_TEXSOURCES DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMFLOCALEDIR
#define DEFAULT_TEXMFLOCALEDIR DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_WEBINPUTS
#define DEFAULT_WEBINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_CWEBINPUTS
#define DEFAULT_CWEBINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_OFMFONTS
#define DEFAULT_OFMFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_OPLFONTS
#define DEFAULT_OPLFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_OVFFONTS
#define DEFAULT_OVFFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_OVPFONTS
#define DEFAULT_OVPFONTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_OTPINPUTS
#define DEFAULT_OTPINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_OCPINPUTS
#define DEFAULT_OCPINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_T4HTINPUTS
#define DEFAULT_T4HTINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEX4HTFONTSET
#define DEFAULT_TEX4HTFONTSET DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEX4HTINPUTS
#define DEFAULT_TEX4HTINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TW_LIBPATH
#define DEFAULT_TW_LIBPATH DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TW_INIPATH
#define DEFAULT_TW_INIPATH DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TTF2TFMINPUTS
#define DEFAULT_TTF2TFMINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_DVIPDFMXINPUTS
#define DEFAULT_DVIPDFMXINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_LUAINPUTS
#define DEFAULT_LUAINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_CLUAINPUTS
//#define DEFAULT_CLUAINPUTS "$TEXMFDOTDIR:$SELFAUTOLOC/lib/{$progname,$engine,}/lua//"
#define DEFAULT_CLUAINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMFSCRIPTS
#define DEFAULT_TEXMFSCRIPTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_JAVAINPUTS
#define DEFAULT_JAVAINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_PERLINPUTS
#define DEFAULT_PERLINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_PYTHONINPUTS
#define DEFAULT_PYTHONINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_RUBYINPUTS
#define DEFAULT_RUBYINPUTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMFCNF
//#define DEFAULT_TEXMFCNF "{$SELFAUTOLOC,$SELFAUTOLOC/share/texmf-local/web2c,$SELFAUTOLOC/share/texmf-dist/web2c,$SELFAUTOLOC/share/texmf/web2c,$SELFAUTOLOC/texmf-local/web2c,$SELFAUTOLOC/texmf-dist/web2c,$SELFAUTOLOC/texmf/web2c,$SELFAUTODIR,$SELFAUTODIR/share/texmf-local/web2c,$SELFAUTODIR/share/texmf-dist/web2c,$SELFAUTODIR/share/texmf/web2c,$SELFAUTODIR/texmf-local/web2c,$SELFAUTODIR/texmf-dist/web2c,$SELFAUTODIR/texmf/web2c,$SELFAUTOGRANDPARENT/texmf-local/web2c,$SELFAUTOPARENT,$SELFAUTOPARENT/share/texmf-local/web2c,$SELFAUTOPARENT/share/texmf-dist/web2c,$SELFAUTOPARENT/share/texmf/web2c,$SELFAUTOPARENT/texmf-local/web2c,$SELFAUTOPARENT/texmf-dist/web2c,$SELFAUTOPARENT/texmf/web2c}"
#define DEFAULT_TEXMFCNF DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEXMF_RESTRICTED_SCRIPTS
#define DEFAULT_TEXMF_RESTRICTED_SCRIPTS DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_MISSFONT_LOG
#define DEFAULT_MISSFONT_LOG DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEX_HUSH
#define DEFAULT_TEX_HUSH DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_TEX
#define DEFAULT_TEX DEFAULT_TEXPATH
#endif

#ifndef DEFAULT_BIBTEX_CSFILE
#define DEFAULT_BIBTEX_CSFILE DEFAULT_TEXPATH
#endif

